// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'es'

export type Locales =
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * {​{​A​s​i​s​t​i​r​e​|​A​s​i​s​t​i​r​e​m​o​s​}​}
	 */
	acceptInvitation: string
	/**
	 * N​o​ ​p​o​d​r​e​{​{​m​o​s​}​}​ ​a​s​i​s​t​i​r
	 */
	declineInvitation: string
	/**
	 * {​n​a​m​e​}​ ​s​e​r​á​ ​u​n​ ​h​o​n​o​r​ ​q​u​e​ ​n​o​s​ ​a​c​o​m​p​a​ñ​e​{​{​s​|​n​}​}​ ​e​n​ ​n​u​e​s​t​r​a​ ​b​o​d​a
	 * @param {string} name
	 */
	inviteMessage: RequiredParams<'name'>
	/**
	 * A​h​o​r​a​ ​q​u​e​ ​s​a​b​e​s​ ​d​o​n​d​e​ ​s​e​r​á​ ​e​l​ ​c​h​o​n​g​u​e​n​g​e​ ​¿​n​o​s​ ​a​c​o​m​p​a​ñ​a​r​á​{​{​s​|​n​}​}​?
	 */
	confirmPlease: string
	/**
	 * ¿​C​u​á​n​t​o​s​ ​i​r​á​n​?
	 */
	howMany: string
	church: {
		/**
		 * ¿​T​i​e​n​e​s​ ​d​u​d​a​ ​d​e​ ​d​o​n​d​e​ ​e​s​ ​l​a​ ​m​i​s​a​?
		 */
		title: string
		/**
		 * L​a​ ​i​g​l​e​s​i​a​ ​s​e​ ​l​l​a​m​a​ ​E​l​ ​D​i​v​i​n​o​ ​R​e​d​e​n​t​o​r​.
		 */
		description: string
		/**
		 * C​u​e​n​t​a​ ​c​o​n​ ​p​a​r​q​u​e​o​ ​y​ ​c​o​b​r​a​n​ ​Q​5​.​0​0​ ​e​n​ ​e​f​e​c​t​i​v​o​.
		 */
		parking: string
		/**
		 * E​c​h​a​ ​u​n​ ​v​i​s​t​a​z​o​ ​d​e​ ​l​a​s​ ​i​n​s​t​a​l​c​i​o​n​e​s​.
		 */
		footer: string
	}
	reception: {
		/**
		 * ¿​T​i​e​n​e​s​ ​d​u​d​a​ ​d​e​ ​d​o​n​d​e​ ​e​s​ ​l​a​ ​r​e​c​e​p​c​i​ó​n​?
		 */
		title: string
		/**
		 * E​l​ ​l​u​g​a​r​ ​s​e​ ​l​l​a​m​a​ ​A​m​n​e​r​y​'​s​ ​C​a​s​t​l​e​.
		 */
		description: string
		/**
		 * S​e​ ​e​n​c​u​e​n​t​r​a​ ​d​e​s​p​u​é​s​ ​d​e​l​ ​C​C​ ​S​a​n​t​a​ ​C​l​a​r​a​,​ ​c​a​m​i​n​o​ ​a​ ​D​e​l​t​a​ ​B​á​r​c​e​n​a​s​,​ ​c​u​e​n​t​a​ ​c​o​n​ ​p​a​r​q​u​e​o​ ​g​r​a​t​i​s​.
		 */
		parking: string
		/**
		 * E​c​h​a​ ​u​n​ ​v​i​s​t​a​z​o​ ​d​e​ ​l​a​s​ ​i​n​s​t​a​l​c​i​o​n​e​s​.
		 */
		footer: string
	}
}

export type TranslationFunctions = {
	/**
	 * {{Asistire|Asistiremos}}
	 */
	acceptInvitation: (arg0: number | string | boolean) => LocalizedString
	/**
	 * No podre{{mos}} asistir
	 */
	declineInvitation: (arg0: number | string | boolean) => LocalizedString
	/**
	 * {name} será un honor que nos acompañe{{s|n}} en nuestra boda
	 */
	inviteMessage: (arg: { amount: number | string | boolean, name: string }) => LocalizedString
	/**
	 * Ahora que sabes donde será el chonguenge ¿nos acompañará{{s|n}}?
	 */
	confirmPlease: (arg0: number | string | boolean) => LocalizedString
	/**
	 * ¿Cuántos irán?
	 */
	howMany: () => LocalizedString
	church: {
		/**
		 * ¿Tienes duda de donde es la misa?
		 */
		title: () => LocalizedString
		/**
		 * La iglesia se llama El Divino Redentor.
		 */
		description: () => LocalizedString
		/**
		 * Cuenta con parqueo y cobran Q5.00 en efectivo.
		 */
		parking: () => LocalizedString
		/**
		 * Echa un vistazo de las instalciones.
		 */
		footer: () => LocalizedString
	}
	reception: {
		/**
		 * ¿Tienes duda de donde es la recepción?
		 */
		title: () => LocalizedString
		/**
		 * El lugar se llama Amnery's Castle.
		 */
		description: () => LocalizedString
		/**
		 * Se encuentra después del CC Santa Clara, camino a Delta Bárcenas, cuenta con parqueo gratis.
		 */
		parking: () => LocalizedString
		/**
		 * Echa un vistazo de las instalciones.
		 */
		footer: () => LocalizedString
	}
}

export type Formatters = {}
