// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'es'

export type Locales =
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * {​{​A​s​i​s​t​i​r​e​|​A​s​i​s​t​i​r​e​m​o​s​}​}
	 */
	acceptInvitation: string
	/**
	 * N​o​ ​p​o​d​r​e​{​{​m​o​s​}​}​ ​a​s​i​s​t​i​r
	 */
	declineInvitation: string
	/**
	 * E​s​t​á​{​{​s​|​n​}​}​ ​c​o​r​d​i​a​l​m​e​n​t​e​ ​i​n​v​i​t​a​d​o​ ​a​ ​l​a​ ​c​e​l​e​b​r​a​c​i​ó​n​ ​d​e​ ​n​u​e​s​t​r​a​ ​b​o​d​a
	 */
	inviteMessage: string
	/**
	 * C​o​n​f​i​r​m​a​n​o​s​ ​s​i​ ​p​o​d​r​á​{​{​s​|​n​}​}​ ​i​r
	 */
	confirmPlease: string
	/**
	 * ¿​C​u​á​n​t​o​s​ ​i​r​á​n​?
	 */
	howMany: string
}

export type TranslationFunctions = {
	/**
	 * {{Asistire|Asistiremos}}
	 */
	acceptInvitation: (arg0: number | string | boolean) => LocalizedString
	/**
	 * No podre{{mos}} asistir
	 */
	declineInvitation: (arg0: number | string | boolean) => LocalizedString
	/**
	 * Está{{s|n}} cordialmente invitado a la celebración de nuestra boda
	 */
	inviteMessage: (arg0: number | string | boolean) => LocalizedString
	/**
	 * Confirmanos si podrá{{s|n}} ir
	 */
	confirmPlease: (arg0: number | string | boolean) => LocalizedString
	/**
	 * ¿Cuántos irán?
	 */
	howMany: () => LocalizedString
}

export type Formatters = {}
